name: Backport
on:
  pull_request:
    branches:
      - master
      - staging

jobs:
  backport:
    runs-on: ubuntu-latest
    name: Backport
    steps:
      # hub コマンドをインストールする
      - name: checkout
        uses: actions/checkout@v2
      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${github.event.pull_request}
        run: |
          hub pull-request -m "Github Actions からプルリクを出す $BRANCH_NAME" -b develop -h master


