name: Backport
on:
  pull_request:
    branches:
      - master
      - staging

jobs:
  backport:
    runs-on: ubuntu-18.04
    name: Backport
    steps:
      - uses: actions/checkout@v2
      - name: Backport
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.ACTIONS }}
          base: master
          branch: develop
          draft: true


