name: Backport
on:
  pull_request:
    branches:
      - master
      - staging

jobs:
  backport:
    runs-on: ubuntu-latest
    name: Backport
    steps:
      # hub コマンドをインストールする
      - name: checkout
        uses: actions/checkout@v2
      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          hub pull-request -m "GITHUB_REF: GITHUB_BASE_REF:" -b develop -h ${{ github.event.pull_request.base.ref }}


