name: Backport
on:
  pull_request:
    branches:
      - master
      - staging

jobs:
  backport:
    runs-on: ubuntu-18.04
    name: Backport
    steps:
      - uses: actions/checkout@v2
      - name: Backport
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        uses: peter-evans/create-pull-request@v3
        with:
          branch: develop


